### ISSUE TITLE
Build of fresh repo fails on Mountain Lion with brew

### ISSUE THREAD

**Issue by puzza007** [okeuday/GEPD#3] opened 2013-03-23 17:18 UTC
Erlang R16B
cmake version 2.8.10.2
boost: stable 1.53.0 (bottled), HEAD

Build log [gist](https://gist.github.com/puzza007/5228529)

**Comment by okeuday** [comment] 2016-08-29 09:49
Pretty sure this is resolved with newer clang.

**Comment by pauloliver-paymark** [comment] 2016-08-29 23:46
Doesn't seem to be on `10.11.5`

```
poliver@Pauls-MacBook-Pro ~/src/GEPD/build (master) $ clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
poliver@Pauls-MacBook-Pro ~/src/GEPD (master) $ mkdir build
poliver@Pauls-MacBook-Pro ~/src/GEPD (master) $ cd build
poliver@Pauls-MacBook-Pro ~/src/GEPD/build (master) $ cmake ..
-- Using OTP lib: /usr/local/Cellar/erlang/19.0.2/lib/erlang/lib - found
-- Using erl_interface version: erl_interface-3.9
-- Using erts version: erts-8.0.2
-- Boost version: 1.61.0
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   test_functions_port_driver_vsn-1

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/poliver/src/GEPD/build
poliver@Pauls-MacBook-Pro ~/src/GEPD/build (master) $ make
Scanning dependencies of target test_functions_port_driver_vsn-1
[ 14%] Building CXX object CMakeFiles/test_functions_port_driver_vsn-1.dir/port_driver.cpp.o
/Users/poliver/src/GEPD/port_driver.cpp:1156:292: error: expected ';' after expression
  ...c->cmd, 0 != 0, c->o._uint64_t); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FUNCTION_ARGUMENT_FROM_TYPE_(c->i.arg0) ) return; case 4: reply_data_...
                                                                                                                                     ^
                                                                                                                                     ;
/Users/poliver/src/GEPD/port_driver.cpp:1156:241: error: no member named 'arg0' in
      'callstate_t::(anonymous struct at /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
  ...!= 0); driver_free(c); return; case 3: reply_data_integer(desc, c->cmd, 0 != 0, c->o._uint64_t); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FUNCT...
                                                                                                                                             ~~~~ ^
/Users/poliver/src/GEPD/port_driver.cpp:1156:285: error: no member named 'arg0' in
      'callstate_t::(anonymous struct at /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
  ...c->cmd, 0 != 0, c->o._uint64_t); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FUNCTION_ARGUMENT_FROM_TYPE_(c->i.arg0) ) return; case 4: reply_data_...
                                                                                                                         ~~~~ ^
/Users/poliver/src/GEPD/port_driver.cpp:1156:599: error: expected ';' after expression
  ...c->cmd, 0 != 0, c->o._float); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FUNCTION_ARGUMENT_FROM_TYPE_(c->i.arg0) ) return; case 7: reply_data_str...
                                                                                                                                  ^
                                                                                                                                  ;
/Users/poliver/src/GEPD/port_driver.cpp:1156:548: error: no member named 'arg0' in
      'callstate_t::(anonymous struct at /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
  ...0 != 0, c->o._uchar); return; case 6: reply_data_double(desc, c->cmd, 0 != 0, c->o._float); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FUNCTION_A...
                                                                                                                                        ~~~~ ^
/Users/poliver/src/GEPD/port_driver.cpp:1156:592: error: no member named 'arg0' in
      'callstate_t::(anonymous struct at /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
  ...reply_data_double(desc, c->cmd, 0 != 0, c->o._float); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FUNCTION_ARGUMENT_FROM_TYPE_(c->i.arg0) ) return...
                                                                                                                                              ~~~~ ^
/Users/poliver/src/GEPD/port_driver.cpp:1156:1525: error: expected ';' after expression
  ...); free(c->o._pchar_len.pchar); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FUNCTION_ARGUMENT_FROM_TYPE_(c->i.arg0) ) return;
                                                                                                                                    ^
                                                                                                                                    ;
/Users/poliver/src/GEPD/port_driver.cpp:1156:1474: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
  ...desc, c->cmd, 0 != 0, c->o._pchar_len.pchar, c->o._pchar_len.length ); free(c->o._pchar_len.pchar); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FU...
                                                                                                                                                ~~~~ ^
/Users/poliver/src/GEPD/port_driver.cpp:1156:1518: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
  ...c->o._pchar_len.length ); free(c->o._pchar_len.pchar); CREATE_FUNCTION_OUTPUT_PROCESS_TYPE_ ( c->i.arg0, GET_FUNCTION_ARGUMENT_FROM_TYPE_(c->i.arg0) ) return;
                                                                                                                                               ~~~~ ^
/Users/poliver/src/GEPD/port_driver.cpp:1186:1407: error: expected ';' after expression
/Users/poliver/src/GEPD/port_driver.cpp:1186:1356: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
/Users/poliver/src/GEPD/port_driver.cpp:1186:1400: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
/Users/poliver/src/GEPD/port_driver.cpp:1186:1451: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
/Users/poliver/src/GEPD/port_driver.cpp:1186:1495: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
/Users/poliver/src/GEPD/port_driver.cpp:1186:2952: error: expected ';' after expression
/Users/poliver/src/GEPD/port_driver.cpp:1186:2901: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
/Users/poliver/src/GEPD/port_driver.cpp:1186:2945: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
/Users/poliver/src/GEPD/port_driver.cpp:1186:2996: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
/Users/poliver/src/GEPD/port_driver.cpp:1186:3040: error: no member named 'arg0' in 'callstate_t::(anonymous struct at
      /Users/poliver/src/GEPD/port_driver.cpp:850:5)'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/test_functions_port_driver_vsn-1.dir/port_driver.cpp.o] Error 1
make[1]: *** [CMakeFiles/test_functions_port_driver_vsn-1.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by okeuday** [comment] 2016-08-31 07:21
I can confirm this on OSX El Capitan with both clang and gcc.  It appears that the clang preprocessor is used for both and is unable to handle boost preprocessor yet.

**Comment by okeuday** [comment] 2016-08-31 23:01
Actually, this is a bug that affects both gcc 5.4.0 and appleclang 7.3.0 in boost/processor (boost 1.58).  There appears to be more than one bug, but one has been filed at https://svn.boost.org/trac/boost/ticket/12426 .

**Comment by okeuday** [comment] 2016-09-01 03:42
The commit https://github.com/okeuday/GEPD/commit/fd38bfa4cc2a5d2eee91ac5fd19dfde53f061179 makes the compilation work, if arity 0 functions aren't used when generation a port driver.  The arity 0 functions depend on the bug filed against boost preprocessor.

**Comment by christopheradams** [comment] 2016-09-20 10:30
Which OS/compiler/boost versions is this project known to build on? I've tried on Ubuntu 14.04 and 16.04, and Debian Wheezy, and couldn't make a go of it.

**Comment by okeuday** [comment] 2016-09-20 20:16
@christopheradams The compilation problem should be only boost >= 1.56.0 when using arity 0 functions while building a port driver (there were boost preprocessor additions into that version which are somewhat broken unfortunately and I filed 2 bugs with boost, but the boost preprocessor lacks active maintenance it appears).  I commented out the arity 0 test functions being used, so it should compile if you get the latest changes.  I will look at a work-around.

**Comment by okeuday** [comment] 2016-09-20 21:20
Ok, now this issue should be finally fixed.  Please tell me if anyone has further problems, otherwise I will close it in a few days.

**Comment by puzza007** [comment] 2016-09-20 22:24
I'm getting https://gist.github.com/puzza007/014455f6d74638f1fce0496d092caf76

**Comment by okeuday** [comment] 2016-09-20 22:57
@puzza007 Yeah, I don't use cmake and I can remove it if necessary, due to lack of support, just try the autoconf/automake approach.

**Comment by puzza007** [comment] 2016-09-20 23:05
👍 builds on el capitan using autoconf/automake

**Comment by christopheradams** [comment] 2016-09-21 03:46
builds now on Ubuntu 14.04 with autoconf

**Comment by okeuday** [comment] 2016-09-21 04:51
Ok, will close this issue.  I removed the cmake build info from the README until it is fixed or removed, but that can be handled separately from this issue.

**Closed by okeuday** 2016-09-21 04:51 UTC
